title: Elingdetanxi
description: Welcome to my website! (Just a try)

url: https://elingdetanxi.github.io/index.html
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Content
    url: /content

social:
  github: elingdetanxi
  #twitter: brianmaierjr
  facebook: Yuan Yan
  #email: brimaidesigns@gmail.com
  linkedin: Yuan Yan

#google_analytics: "UA-58263416-1"

disqus:
    shortname: yy
